### ISSUE TITLE
GET User Transactions - options not used and error msg

### ISSUE THREAD

**Issue by thisiscr** [craigrich/yodlee#1]
Hi Craig,

Noticed that the Options param (opt) is not actually being used in  your getTransactions implementation and assuming this is not the intended behaviour :)

Also getting this error when attempting your readme example as is:
`{"errorOccurred":"true","exceptionType":"com.yodlee.core.IllegalArgumentValueException","referenceCode":"_b9fc3eb2-da16-4f66-89ef-1aec0cbadc57","message":"Invalid argument value: Container type cannot be null"}`

Otherwise neat job on the wrapper!

Thanks,
The Other Craig

**Comment by craigrich** [comment]
Hi @thisiscr, 

Thanks for the heads up! I've updated the opts - it looks like Yodlee's API switched the 'resultRangeEndNumber' and 'resultRangeStartNumber' to 'endNumber' and 'startNumber'. All fixed :)
